[package]
authors = ["Jonas Platte <jplatte+git@posteo.de>"]
name = "mycelium"
version = "0.1.0"

[dependencies]
gio = "0.1.3"
mime_guess = "1.8.1"

[dependencies.gtk]
features = ["v3_14"]
version = "0.1.3"
