[package]
authors = ["Jonas Platte <jplatte+git@posteo.de>"]
name = "mycelium"
version = "0.1.0"
edition = "2018"

[dependencies]
dirs = "2.0.1"
gio = "0.7.0"
mime_guess = "1.8.7"

[dependencies.gtk]
features = ["v3_16"]
version = "0.7.0"
